services:

  mongodb:
      image: 'mongo'
      volumes:
        - data:/data/db
      restart: always
      env_file:
        - ./env/mongo.env
      # networks:
      #   - goals-net
    # frontend:
    #   image: 

  backend:
    build: ./backend
    # build:
    #   context: ./backend
      # dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    restart: always
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb


  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src 
    stdin_open: true
    tty: true
    restart: always
 
    depends_on:
      - backend
   
 

volumes:
  data:
  logs:

  