services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
       - ./src:/var/www/html:delegated
       - ./src:/var/www/html/storage/logs
       - ./src:/var/www/html/storage/framework/sessions
       - ./src:/var/www/html/storage/framework/views
       - ./src:/var/www/html/storage/framework/cache
   
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
     - ./mysql/.env
  
  composer:
    build: 
      context: ./composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    # depends_on:
    #   - mysql
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html


